const express = require('express');
const router = express.Router();
const passport = require('passport');
console.log("Router Loaded");
const dashController = require('../controllers/dash_controller');
const contestController = require('../controllers/contest_controller');
const notFoundController = require('../controllers/404_controller');
router.get('/',passport.checkAuthentication,dashController.home);
router.use('/users', require('./user'));
router.use('/problem',require('./problem'));
router.use('/category',require('./category'));
router.use('/practice',require('./practice'));
router.use('/search',require('./search'));
router.get('/contests',passport.checkAuthentication,contestController.contestPage);
router.use('/documents',require('./documents'));
router.use('/code',require('./code'));
router.use('/tasklist',require('./tasklist'));
router.use('/favourite',require('./favourite'));
router.get('*',notFoundController.notFound);
module.exports = router;