const express = require('express');
const router = express.Router();
const passport = require('passport');
console.log("Router Loaded");
const dashController = require('../controllers/dash_controller');
router.get('/',passport.checkAuthentication,dashController.home);
router.use('/users', require('./user'));
router.use('/problem',require('./problem'));
router.use('/category',require('./category'));
router.use('/search',require('./search'));
module.exports = router;